name: MacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build MeshLab (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        brew install libomp
        npm install -g appdmg
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        echo  ::set-output name=date::"$(cat ML_VERSION)"
    - name: Configure and Build
      run: |
        sh scripts/macos/macos_build.sh
    - name: Deploy
      run: |
        sh scripts/macos/macos_deploy.sh
    - name: Create DMG
      run: |
         sh scripts/macos/macos_dmg.sh
         mv src/install/MeshLab${{steps.envs.outputs.date}}.dmg src/install/MeshLab${{steps.envs.outputs.date}}-macos.dmg
    - name: Upload DMG
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_macos_dmg_cmake
        path: src/install/MeshLab${{steps.envs.outputs.date}}-macos.dmg
