name: Windows

on: [push, pull_request]

jobs:
  windows_build:
    name: Build MeshLab (Windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Download Jom
      run: |
        Invoke-WebRequest -Uri "http://download.qt.io/official_releases/jom/jom_1_1_3.zip" -OutFile "jom_1_1_3.zip"
        New-Item -Name "jom" -ItemType "directory"
        Expand-Archive -Path jom_1_1_3.zip -DestinationPath .\jom
        echo "::add-path::$(Get-Location)\jom"
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: xmlpatterns
    - name: Setup env variables
      id: envs
      run: |
        echo "::set-output name=date::$(type ML_VERSION)"
    - name: Configure and Build
      shell: bash
      run: |
        sh scripts/windows/windows_build.sh
    - name: Deploy
      shell: bash
      run: |
        sh scripts/windows/windows_deploy.sh
    - name: NSIS script
      shell: bash
      run: |
        sh scripts/windows/resources/windows_nsis_script.sh
    - name: Create Installer
      uses: joncloud/makensis-action@v1
      with:
        script-file: "src/install/meshlab_final.nsi"
    - name: Rename Installer
      shell: bash
      run: |
        mv src/install/MeshLab${{steps.envs.outputs.date}}.exe  src/MeshLab${{steps.envs.outputs.date}}-windows_cmake.exe
    - name: Uploading MeshLab Portable
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_windows_portable_cmake
        path: src/install
    - name: Upload Meshlab Installer
      uses: actions/upload-artifact@v1
      with:
        name: meshlab_windows_installer_cmake
        path: src/MeshLab${{steps.envs.outputs.date}}-windows_cmake.exe
